apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml
  - sample-service.yml
  - bootstrap-cluster-issuer.yml
  - coredns-configmap.yml



